#!/usr/bin/env python3
# Displays file sequences in a compact representation.

import sys
from ftplib import test
from pathlib import Path
import logging

from lsslib import (get_padding, get_unpadded_framenumber, get_endframe, get_startframe, get_frame_range_total,
                    is_contiguous, get_missing_frames)

logger = logging.getLogger("MAIN")
logging.basicConfig(level=logging.INFO, format="[%(levelname)s %(name)s]: %(message)s")


# Get file path from command line
try:
    path = sys.argv[1]
    path += "/"
except IndexError:
    path = "./"
logger.info("Reading files at: " + path)

# Read files into a list and sort
files = []
for file in Path(path).iterdir():
    if not file.name.startswith("."):  # ignore hidden files like ls -1 does
        files.append(file)
files = sorted(files)

# TEST
get_startframe(files)
get_endframe(files)
get_frame_range_total(files)
test = is_contiguous(files)
get_padding(files)

logger.info("start frame: " + str(get_startframe(files)))
logger.info("end frame: " + str(get_endframe(files)))
logger.info("frame range total: " + str(get_frame_range_total(files)))
logger.info(f"Is contiguous: {test}")
