#!/usr/bin/env python3

import sys
from pathlib import Path

from lsslib import core

# Get filepath
try:
    path = sys.argv[1]
except IndexError:
    path = "./"

# TODO: Check if directory exists and is empty. Don't overwrite.
# TODO: Check if directory exists. If not, create.
