#!/usr/bin/env python3
# Displays file sequences in a compact representation.

import sys
from configparser import MissingSectionHeaderError
from pathlib import Path
import logging
from sys import is_stack_trampoline_active

from lsslib import get_padding, get_unpadded_framenumber, get_endframe, get_startframe, get_frame_range, is_contiguous, get_missing_frames

logger = logging.getLogger("MAIN")
logging.basicConfig(level=logging.INFO, format="[%(levelname)s %(name)s]: %(message)s")


# Get file path from command line
try:
    path = sys.argv[1]
    path += "/"
except IndexError:
    path = "./"
logger.info("Reading files at: " + path)

# Read files into a list and sort
files = []
for file in Path(path).iterdir():
    if not file.name.startswith("."):  # ignore hidden files like ls -1 does
        files.append(file)
files = sorted(files)
