#!/usr/bin/env python3
# Generates various sequences of files to be used as a test data set for the lss tool.

import logging
import sys
import os
from pathlib import Path

from lsslib.sequence import seq_create

logger = logging.getLogger("MAIN")
logging.basicConfig(level=logging.INFO, format="[%(levelname)s %(name)s]: %(message)s")


# Get file path from command line
path = sys.argv[1] if len(sys.argv) > 1 else "."
path = os.path.join(path, "")  # ensures trailing slash
logger.info("Creating files at: %s", path)

if Path(path).is_dir():
    # Create a contigous sequenece of files with 4-padded frames.
    seq_create("seq100", 0, 4, path=path)
    
    # Create a discontigous sequence of files with 4-padded frames.
    seq_create("seq1600", 1, 3, path=path)
    seq_create("seq1600", 5, 7, path=path)
    
    # Create a sequence of files with step of 5.
    seq_create("seq2000", 0, 15, step=5, path=path)
    
    # Create a sequence of files with frames of different padding.
    seq_create("seq3600", 1, 3, padding=3, path=path)
    seq_create("seq3600", 1, 3, padding=4, path=path)
    
    # Create a sequence a non-padded sequence.
    seq_create("seq3800", 0, 3, padding=0, path=path)
    
    # Create other formatted files.
    seq_create("2000.0220.bty_env_01", 0, 21, step=2, path=path)

else:
    logger.error("Path does not exist. No files created.")
    sys.exit(1)

